package go_pay247

type BankCode struct {
	Currency string `json:"currency"`
	Code     string `json:"code"`
	Name     string `json:"name"`
}

var Pay247BankCodes = []BankCode{
	{Currency: "PHP", Code: "GCASH", Name: "Gcash"},
	{Currency: "PHP", Code: "BPI", Name: "BPI Bank"},
	{Currency: "PHP", Code: "UNIBANK", Name: "BDO Unibank"},
	{Currency: "PHP", Code: "MBT", Name: "Metropolitan Bank and Trust Co"},
	{Currency: "PHP", Code: "LBOB", Name: "LANDBANK / OFBank"},
	{Currency: "PHP", Code: "SBC", Name: "Security Bank Corporation"},
	{Currency: "PHP", Code: "UBP", Name: "Union Bank of the Philippines"},
	{Currency: "PHP", Code: "PNB", Name: "Philippine National Bank"},
	{Currency: "PHP", Code: "CBC", Name: "China Banking Corporation"},
	{Currency: "PHP", Code: "EWBC", Name: "East West Banking Corporation"},
	{Currency: "PHP", Code: "RCBC", Name: "RCBC/DiskarTech"},
	{Currency: "PHP", Code: "UCPB", Name: "United Coconut Planters Bank (UCPB)"},
	{Currency: "PHP", Code: "PSB", Name: "Philippine Savings Bank"},
	{Currency: "PHP", Code: "AUB", Name: "Asia United Bank Corporation"},
	{Currency: "PHP", Code: "PBC", Name: "Philippine Bank of Communications"},
	{Currency: "PHP", Code: "DBP", Name: "Development Bank of the Philippines"},
	{Currency: "PHP", Code: "AB", Name: "ALLBANK(A Thirft Bank)"},
	{Currency: "PHP", Code: "Asenso", Name: "Asenso"},
	{Currency: "PHP", Code: "BM", Name: "Bangko Mabuhay"},
	{Currency: "PHP", Code: "BC", Name: "Bank of Commerce"},
	{Currency: "PHP", Code: "BK", Name: "BanKo,A Subsidiary of BPI"},
	{Currency: "PHP", Code: "BAYAD", Name: "Bayad"},
	{Currency: "PHP", Code: "BNB", Name: "BDO NeTwork Bank"},
	{Currency: "PHP", Code: "CB", Name: "Camalig Bank"},
	{Currency: "PHP", Code: "CARD Bank", Name: "CARD Bank"},
	{Currency: "PHP", Code: "CLB", Name: "Cebuana Lhuillier Bank / Cebuana Xpress"},
	{Currency: "PHP", Code: "CBS", Name: "China Bank Savings"},
	{Currency: "PHP", Code: "COINS", Name: "Coins.ph (DCPay)"},
	{Currency: "PHP", Code: "CTBC", Name: "CTBC Bank (Philippines) Corporation"},
	{Currency: "PHP", Code: "DCDB", Name: "Dumaguete City Development Bank"},
	{Currency: "PHP", Code: "DB", Name: "Dungganon Bank"},
	{Currency: "PHP", Code: "ESB", Name: "Equicom Savings Bank"},
	{Currency: "PHP", Code: "GP", Name: "GrabPay"},
	{Currency: "PHP", Code: "IB", Name: "ING Bank N.V."},
	{Currency: "PHP", Code: "ISLA", Name: "ISLA Bank"},
	{Currency: "PHP", Code: "JC", Name: "JuanCash"},
	{Currency: "PHP", Code: "Komo", Name: "Komo / EastWest Rural Bank"},
	{Currency: "PHP", Code: "LSB", Name: "Legazpi Saving Bank"},
	{Currency: "PHP", Code: "MBS", Name: "Malayan Bank Saving and Mortage Bank"},
	{Currency: "PHP", Code: "MBP", Name: "Maybank Philippnies"},
	{Currency: "PHP", Code: "MCCB", Name: "Mindanao Consolidated CoopBank"},
	{Currency: "PHP", Code: "NB", Name: "Netbank"},
	{Currency: "PHP", Code: "OP", Name: "OmniPay"},
	{Currency: "PHP", Code: "PRB", Name: "Partner Rural Bank"},
	{Currency: "PHP", Code: "PMP", Name: "PayMaya Philippines"},
	{Currency: "PHP", Code: "PBB", Name: "Philippine Business Bank"},
	{Currency: "PHP", Code: "PTC", Name: "Philippine Trust Company"},
	{Currency: "PHP", Code: "PDB", Name: "Producers Bank"},
	{Currency: "PHP", Code: "QB", Name: "Queenbank"},
	{Currency: "PHP", Code: "QCRB", Name: "Quezon Capital Rural Bank"},
	{Currency: "PHP", Code: "RSB", Name: "RCBC Saving Bank"},
	{Currency: "PHP", Code: "RBB", Name: "Robinsons Bank Corporation"},
	{Currency: "PHP", Code: "SB", Name: "Seabank"},
	{Currency: "PHP", Code: "SP", Name: "ShopeePay"},
	{Currency: "PHP", Code: "SCB", Name: "Standard Chartered Bank"},
	{Currency: "PHP", Code: "STP", Name: "Starpay"},
	{Currency: "PHP", Code: "SLB", Name: "Sterling Bank of Asia"},
	{Currency: "PHP", Code: "SSB", Name: "Sun Savings Bank"},
	{Currency: "PHP", Code: "TC", Name: "TayoCash"},
	{Currency: "PHP", Code: "USB", Name: "UCPB Savings Bank"},
	{Currency: "PHP", Code: "USSC", Name: "USSC Monet Services"},
	{Currency: "PHP", Code: "VB", Name: "Veterans Bank"},
	{Currency: "PHP", Code: "WDB", Name: "Wealth Development Bank"},
	{Currency: "PHP", Code: "OWNB", Name: "OWN Bank"},
	{Currency: "PHP", Code: "UNOB", Name: "UNO Bank"},
	{Currency: "PHP", Code: "UMS", Name: "USSC Money Services"},
	{Currency: "PHP", Code: "UDB", Name: "UnionDigital Bank"},
	{Currency: "PHP", Code: "TPI", Name: "TraxionPay/DigiCOOP/COOPNET TP"},
	{Currency: "PHP", Code: "TDB", Name: "Tonik Bank"},
	{Currency: "PHP", Code: "SPI", Name: "SpeedyPay/eMango Pay"},
	{Currency: "PHP", Code: "SME", Name: "CARD SME Bank"},
	{Currency: "PHP", Code: "RBG", Name: "Rural Bank of Guinobatan / Asenso"},
	{Currency: "PHP", Code: "PPS", Name: "PalawanPay"},
	{Currency: "PHP", Code: "PNS", Name: "PNB Savings Bank"},
	{Currency: "PHP", Code: "PDAX", Name: "PDAX"},
	{Currency: "PHP", Code: "PAS", Name: "Pacific Ace Savings Bank"},
	{Currency: "PHP", Code: "MAYA", Name: "Maya Bank, Inc."},
	{Currency: "PHP", Code: "LDB", Name: "Luzon Development Bank"},
	{Currency: "PHP", Code: "IRI", Name: "I-Remit / iCASH"},
	{Currency: "PHP", Code: "IEM", Name: "Infoserve / Nationlink"},
	{Currency: "PHP", Code: "GOT", Name: "GoTyme Bank"},
	{Currency: "PHP", Code: "ENTRPERB", Name: "Entrepreneur Rural Bank, Inc."},
	{Currency: "PHP", Code: "CPI", Name: "CIMB Philippines, Inc."},
	{Currency: "PHP", Code: "CIS", Name: "CIS Bayad Center / Bayad"},
	{Currency: "PHP", Code: "CBI", Name: "Cantilan Bank"},
	{Currency: "PHP", Code: "BCH", Name: "Bank of China"},
	{Currency: "PHP", Code: "APY", Name: "Alipay / Lazada Wallet"},
	{Currency: "PHP", Code: "GHP", Name: "Gpay Network Ph, Inc. / GrabPay"},
	{Currency: "PHP", Code: "CAM", Name: "CARD MRI"},
	{Currency: "PHP", Code: "BIU", Name: "Binangonan Rural Bank / BRBDigital"},
	{Currency: "PHP", Code: "BFB", Name: "Banana Fintech / BananaPay"},
	{Currency: "PHP", Code: "BDOUI", Name: "Banco De Oro Unibank, Inc (BDO)"},
	{Currency: "PHP", Code: "TOK", Name: "TokTok Wallet Inc"},
	{Currency: "PHP", Code: "WISE", Name: "Wise Pilipinas, Inc"},
	{Currency: "PHP", Code: "PAYLOROAPP", Name: "payloroapp"},
	{Currency: "PHP", Code: "ZYBIT", Name: "Zybi Tech Inc"},
	{Currency: "PHP", Code: "YSB", Name: "Yuanta Savings Bank, Inc."},
	{Currency: "PHP", Code: "QCDB", Name: "Queen City Development Bank, Inc."},
	{Currency: "PHP", Code: "EWBI", Name: "East West Rural Bank, Inc."},
	{Currency: "PHP", Code: "CTBCI", Name: "CTBC Bank (Philippines), Inc."},
	{Currency: "PHP", Code: "BOTPI", Name: "Bank Of The Philippine Islands"},
	{Currency: "PHP", Code: "BPIDB", Name: "BPI Direct Banko, Inc., A Savings Bank"},
	{Currency: "PHP", Code: "ALLIED", Name: "Allied Banking Corp"},
}
